version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  spring-app:
    container_name: nicole-spring-app-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5558:5558"
    depends_on:
      - db
    environment:
      POSTGRESQL_SERVER: db
      POSTGRESQL_PORT: 5432
      POSTGRESQL_DB: db
      POSTGRESQL_USERNAME: admin
      POSTGRESQL_PASSWORD: admin
      SERVER_PORT: 5558
